dataset:
  name: 'exid'
  description: '6_merzenich_rather'
  import_dir: '../Datasets/exiD-dataset-v2.0/data'
  export_dir: '../Datasets/exid/'
  map_export_dir: '../Datasets/exid/Maps/78-92.pickle'
  lanelet2_file_dir: '../Datasets/exiD-dataset-v2.0/maps/lanelet2/6_merzenich_rather.osm'
  lane_markings_yml_dir:  '../Datasets/exiD-dataset-v2.0/maps/!lane_markings/6_merzenich_rather.yaml'
  # in dataset with large number of data files, we use fileranges and filestring
  fileranges: range(78,93) 
  filestring: "{}_tracks.csv"
  dataset_fps: 25
  desired_fps: 5
  UTMZone: '32'
  xUtmOrigin: 325298.1 # lat 50.847664
  yUtmOrigin: 5635819.6 # lon 6.518251
ordered_preprocess_functions: # 'all' means function is designed to be applied to all data files, 'one' means it should be iterated on each data files.
  # Utility functtions:
  ##- ['self.export_data()', 'all'] # optional
  ##- ['self.import_processed_data()', 'all'] #optional
  ##- ['exid.visualise_tracks', 'one']
  ##- ['exid.plot_traj', 'one']
  ##- ['self.reduce_fps()', 'all']
  
  # Required functions:
  - ['self.match_columns()', 'all']
  - ['self.initialise_df()', 'all']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['exid.hdmaps2lane_markings', 'all'] 
  - ['exid.convert2frenet', 'one']
  - ['exid.get_lane_ids', 'one']
  - ['ngsim.calc_vel_acc', 'one']
  - ['self.overwrite_data(source = "track")', 'all']
  - ['self.reduce_fps()', 'all']
  - ['exid.calc_svs_povl', 'one']
  - ['self.overwrite_data(source = "frame")', 'all']
  - ['self.export_data()', 'all']
  
# Match new dataset columns to highD columns in use for prediction model. None if there is no matchig
columns:
  # These are the columns essential for conversion: frame, id, x,y 
  FRAME: "frame"
  TRACK_ID: "trackId"
  X: xCenter
  Y: yCenter
  X_VELOCITY: xVelocity #lonVelocity
  Y_VELOCITY: yVelocity #latVelocity
  X_ACCELERATION: xAcceleration #lonAcceleration 
  Y_ACCELERATION: yAcceleration #latAcceleration
  D: None #cross track
  S: None #along track
  D_VELOCITY: None
  S_VELOCITY: None
  D_ACCELERATION: None
  S_ACCELERATION: None
  WIDTH: 'length'
  HEIGHT: 'width'
  PRECEDING_ID: None
  FOLLOWING_ID: None
  LEFT_VEHICLE1_ID: None
  LEFT_VEHICLE2_ID: None
  LEFT_VEHICLE3_ID: None
  RIGHT_VEHICLE1_ID: None
  RIGHT_VEHICLE2_ID: None
  RIGHT_VEHICLE3_ID: None
  LEFT_CLOSE_PRECEDING_ID: None
  LEFT_FAR_PRECEDING_ID: None
  LEFT_CLOSE_FOLLOWING_ID: None
  LEFT_FAR_FOLLOWING_ID: None
  RIGHT_CLOSE_PRECEDING_ID: None
  RIGHT_FAR_PRECEDING_ID: None
  RIGHT_CLOSE_FOLLOWING_ID: None
  RIGHT_FAR_FOLLOWING_ID: None
  LANE_ID: None
  Y2LANE: None
  LANE_WIDTH: None