dataset:
  name: 'exid'
  description: '2_aachen_brand'
  import_dir: '../../Dataset/exiD-dataset-v2.0/data'
  export_dir: '../../Dataset/exid/'
  # in dataset with large number of data files, we use fileranges and filestring
  fileranges: range(39,53)
  filestring: "{}_tracks.csv"
  fps: 25
visualisation:
  image_width: tbd #in meters
  image_height: tbd
  x_bias: 10
  y_bias: 3
ordered_preprocess_functions:
  - 'self.export_data()'
  #- 'self.import_processed_data()'
  #- 'exid.hdmaps2lane_markings'
meta_data:
  lanelet2_file_dir: '../../Dataset/exiD-dataset-v2.0/maps/lanelet2/2_aachen_brand.osm'
  lane_markings_yml_dir:  '../../Dataset/exiD-dataset-v2.0/maps/!lane_markings/2_aachen_brand.yaml'
# These are the columns essential for conversion: frame, id, x,y (in any coordinates/units)
essential_columns:
  FRAME: "frame"
  TRACK_ID: "trackId"
  X: 'xCenter'
  Y: 'yCenter'
# Match new dataset columns to highD columns in use for prediction model. None if there is no matchig
matched_columns:
  X_VELOCITY: lonVelocity
  Y_VELOCITY: latVelocity
  X_ACCELERATION: lonAcceleration 
  Y_ACCELERATION: latAcceleration
  WIDTH: 'length'
  HEIGHT: 'width'
  PRECEDING_ID: None
  FOLLOWING_ID: None
  LEFT_PRECEDING_ID: None
  LEFT_ALONGSIDE_ID: None
  LEFT_FOLLOWING_ID: None
  RIGHT_PRECEDING_ID: None
  RIGHT_ALONGSIDE_ID: None
  RIGHT_FOLLOWING_ID: None
  LANE_ID: 'None'
