dataset:
  name: 'exid'
  description: '2_aachen_brand'
  import_dir: '../../Dataset/exiD-dataset-v2.0/data'
  export_dir: '../../Dataset/exid/'
  # in dataset with large number of data files, we use fileranges and filestring
  fileranges: range(39,40) #range(39,53)
  filestring: "{}_tracks.csv"
  fps: 25
  UTMZone: '32U'
  xUtmOrigin: 298089.6
  yUtmOrigin: 5626462.9
  latOrigin: 50.75476341873654 
  lonOrigin: 6.137354674124027 
visualisation:
  image_width: 0 #tbd in meters
  image_height: 0
  x_bias: 10
  y_bias: 3
ordered_preprocess_functions: # 'all' means function is designed to be applied to all data files, 'one' means it should be iterated on each data files.
  - ['self.match_columns()', 'all']
  - ['self.initialise_df()', 'all']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['self.export_data()', 'all']
  - ['self.import_processed_data()', 'all']
  - ['exid.hdmaps2lane_markings', 'one']
  - ['exid.convert2frenet', 'one']
  - ['exid.get_lane_ids', 'one']
  - ['self.overwrite_data(source = "track")', 'all']
  #- ['exid.visualise_tracks', 'one']
  
  - ['self.export_data()', 'all']
  - ['self.import_processed_data()', 'all']
  - ['exid.calc_svs', 'one']
  - ['self.overwrite_data(source = "frame")', 'all']
  - ['exid.visualise_tracks', 'one']
  - ['self.export_data()', 'all']
  #- ['self.import_processed_data()', 'all']
  
meta_data:
  lanelet2_file_dir: '../../Dataset/exiD-dataset-v2.0/maps/lanelet2/2_aachen_brand.osm'
  lane_markings_yml_dir:  '../../Dataset/exiD-dataset-v2.0/maps/!lane_markings/2_aachen_brand.yaml'
  lane_markings_export_file: '../lane_marking.pkl'
# Columns to keep while they are not necessary matching
unmatched_columns: 
  #- laneletId # to know which lanelet we are in
  #- laneChange # a trigger to know a lane change occurs
  #- lonLaneletPos # longitudinal distance of vehicle center to start of lanelet
  #- latLaneCenterOffset # lateral distance of center of vehicle to center of lanelet
  #- laneletLength
  - xCenter 
  - yCenter
# Match new dataset columns to highD columns in use for prediction model. None if there is no matchig
matched_columns:
  # These are the columns essential for conversion: frame, id, x,y 
  FRAME: "frame"
  TRACK_ID: "trackId"
  X: None
  Y: None
  X_VELOCITY: lonVelocity
  Y_VELOCITY: latVelocity
  X_ACCELERATION: lonAcceleration 
  Y_ACCELERATION: latAcceleration
  WIDTH: 'length'
  HEIGHT: 'width'
  PRECEDING_ID: None
  FOLLOWING_ID: None
  LEFT_PRECEDING_ID: None
  LEFT_ALONGSIDE_ID: None
  LEFT_FOLLOWING_ID: None
  RIGHT_PRECEDING_ID: None
  RIGHT_ALONGSIDE_ID: None
  RIGHT_FOLLOWING_ID: None
  LANE_ID: 'None'
  LANE_WIDTH: laneWidth