dataset:
  name: 'm40j15'
  description: 'N/A'
  import_dir: '../Datasets/m40/raw'
  export_dir: '../Datasets/m40/processed'
  map_import_dir: '../Datasets/m40/maps/j15.npy'
  map_export_dir: '../Datasets/m40/maps/j15_lms.yaml'
  # in dataset with large number of data files, we use fileranges and filestring
  fileranges: range(1,207) #range(1,19) 
  filestring: "Tracked_{}.csv"
  dataset_fps: 10
  desired_fps: 5
ordered_preprocess_functions: # 'all' means function is designed to be applied to all data files, 'one' means it should be iterated on each data files.
  # Utility functtions:
  ##- ['self.export_data()', 'all'] # optional
  ##- ['self.import_processed_data()', 'all'] #optional
  ##- ['exid.visualise_tracks', 'one']
  ##- ['exid.plot_traj', 'one']
  ##- ['self.reduce_fps()', 'all']
  
  # Required functions:
  - ['self.match_columns()', 'all']
  - ['self.initialise_df()', 'all']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['m40.m40_preprocess', 'one']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['m40.filter_bboxes', 'one']
  - ['m40.extract_lms', 'all'] 
  - ['exid.convert2frenet', 'one']
  - ['exid.get_lane_ids', 'one']
  - ['ngsim.calc_vel_acc', 'one']
  - ['self.overwrite_data(source = "track")', 'all']
  - ['self.reduce_fps()', 'all']
  - ['exid.calc_svs_povl', 'one']
  - ['self.overwrite_data(source = "frame")', 'all']
  #- ['exid.visualise_tracks', 'one']
  #- ['exid.plot_traj', 'one']
  #- ['m40.visualise_measurements', 'one']
  - ['self.export_data()', 'all']
  

# Match new dataset columns to highD columns in use for prediction model. None if there is no matchig
columns:
  # These are the columns essential for conversion: frame, id, x,y 
  FRAME: 'time'
  TRACK_ID: 'id'
  X: 'x'
  Y: 'y'
  X_VELOCITY: 'vx' #lonVelocity
  Y_VELOCITY: 'vy' #latVelocity
  X_ACCELERATION: 'ax' #lonAcceleration 
  Y_ACCELERATION: 'ay' #latAcceleration
  D: None #cross track
  S: None #along track
  D_VELOCITY: None
  S_VELOCITY: None
  D_ACCELERATION: None
  S_ACCELERATION: None
  WIDTH: 'bbx'
  HEIGHT: 'bby'
  HEADING: None
  PRECEDING_ID: None
  FOLLOWING_ID: None
  LEFT_VEHICLE1_ID: None
  LEFT_VEHICLE2_ID: None
  LEFT_VEHICLE3_ID: None
  RIGHT_VEHICLE1_ID: None
  RIGHT_VEHICLE2_ID: None
  RIGHT_VEHICLE3_ID: None
  LEFT_CLOSE_PRECEDING_ID: None
  LEFT_FAR_PRECEDING_ID: None
  LEFT_CLOSE_FOLLOWING_ID: None
  LEFT_FAR_FOLLOWING_ID: None
  RIGHT_CLOSE_PRECEDING_ID: None
  RIGHT_FAR_PRECEDING_ID: None
  RIGHT_CLOSE_FOLLOWING_ID: None
  RIGHT_FAR_FOLLOWING_ID: None
  LANE_ID: None
  Y2LANE: None
  LANE_WIDTH: None