dataset:
  name: 'NGSIM2'
  import_dir: '../Datasets/NGSIM/Raws'
  export_dir: '../Datasets/NGSIM/'
  map_export_dir: '../Datasets/NGSIM/ngsim2.pickle'
  dataset_fps: 10
  desired_fps: 5
  filenames: ['04.csv','05.csv','06.csv']
  us101: [False, False, False, True, True, True]
  lane_markings: [[],[],[],[],[],[]]
  image_width: 600 #in meters
  image_height: 100
  x_bias: 10
  y_bias: 3
ordered_preprocess_functions:
  #['self.match_columns()', 'all']
  #['self.initialise_df()', 'all']
  #['self.overwrite_data(source = 'df')', 'all']
  #- ['self.export_data()', 'all']
  #- ['self.import_processed_data()', 'all']
  - ['self.match_columns()', 'all'] #Required
  - ['self.initialise_df()', 'all'] #Required
  - ['self.overwrite_data(source = "df")', 'all'] # Required
  - ['ngsim.relocate_tracking_point' , 'one']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['ngsim.traj_smoothing', 'one']
  - ['ngsim.calc_vel_acc', 'one']
  - ['ngsim.visualise_measurements', 'one']
  - ['self.overwrite_data(source = "track")', 'all']
  - ['ngsim.estimate_lane_markings' , 'all']
  - ['ngsim.update_lane_ids', 'one']
  - ['self.overwrite_data(source = "track")', 'all']
  - ['ngsim.calc_svs', 'one']
  - ['self.overwrite_data(source = "frame")', 'all']
  - ['ngsim.convert_units', 'one']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['self.export_data()', 'all']
  #- ['self.import_processed_data()', 'all']
  #- ['ngsim.visualise_tracks', 'one']
  - ['self.export_statics_metas()', 'all']
# Match new dataset columns to highD columns in use for prediction model. None if there is no matchig
columns:
  FRAME: "Frame_ID"
  TRACK_ID: "Vehicle_ID"
  X: 'Local_Y'
  Y: 'Local_X'
  X_VELOCITY: None
  Y_VELOCITY: None
  X_ACCELERATION: None 
  Y_ACCELERATION: None
  WIDTH: 'v_Length'
  HEIGHT: 'v_Width'
  PRECEDING_ID: None
  FOLLOWING_ID: None
  LEFT_PRECEDING_ID: None
  LEFT_ALONGSIDE_ID: None
  LEFT_FOLLOWING_ID: None
  RIGHT_PRECEDING_ID: None
  RIGHT_ALONGSIDE_ID: None
  RIGHT_FOLLOWING_ID: None
  LANE_ID: 'Lane_ID'