dataset:
  name: 'NGSIM'
  import_dir: '../../Dataset/NGSIM/Raws'
  export_dir: '../../Dataset/NGSIM/'
  filenames: ['01.csv','02.csv','03.csv','04.csv','05.csv','06.csv']
  us101: [False, False, False, True, True, True]
  fps: 10
visualisation:
  image_width: 600 #in meters
  image_height: 100
  x_bias: 10
  y_bias: 3
ordered_preprocess_functions:
  
  - ['ngsim.relocate_tracking_point' , 'single']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['ngsim.traj_smoothing', 'single']
  - ['ngsim.calc_vel_acc', 'single']
  #- ['ngsim.visualise_measurements', 'single']
  - ['self.overwrite_data(source = "track")', 'all']
  - ['ngsim.estimate_lane_markings' , 'single']
  - ['ngsim.update_lane_ids', 'single']
  - ['self.overwrite_data(source = "track")', 'all']
  - ['ngsim.calc_svs', 'single']
  - ['self.overwrite_data(source = "frame")', 'all']
  - ['ngsim.convert_units', 'single']
  - ['self.overwrite_data(source = "df")', 'all']
  - ['self.export_data()', 'all']
  #- ['self.import_processed_data()', 'all']
  #- ['ngsim.visualise_tracks', 'single']
  - ['self.export_statics_metas()', 'all']
meta_data:
  lane_markings: [[],[],[],[],[],[]]
# These are the columns essential for conversion: frame, id, x,y (in any coordinates/units)
essential_columns:
  FRAME: "Frame_ID"
  TRACK_ID: "Vehicle_ID"
  X: 'Local_Y'
  Y: 'Local_X'
# Match new dataset columns to highD columns in use for prediction model. None if there is no matchig
matched_columns:
  X_VELOCITY: None
  Y_VELOCITY: None
  X_ACCELERATION: None 
  Y_ACCELERATION: None
  WIDTH: 'v_Length'
  HEIGHT: 'v_Width'
  PRECEDING_ID: None
  FOLLOWING_ID: None
  LEFT_PRECEDING_ID: None
  LEFT_ALONGSIDE_ID: None
  LEFT_FOLLOWING_ID: None
  RIGHT_PRECEDING_ID: None
  RIGHT_ALONGSIDE_ID: None
  RIGHT_FOLLOWING_ID: None
  LANE_ID: 'Lane_ID'